- name: 创建mysql用户
  user: name=mysql system=True

- name: 准备安装目录
  file: name=/application state=directory

- name: 检查mysql是否部署
  stat: path={{ mysql_dir }}
  register: p

- name: 下发数据库安装包
  unarchive: src={{ base_dir }}/mysql-5.6.42-linux-glibc2.12-x86_64.tar.gz dest=/application
  when: p.stat.isreg is not defined
  tags: pull_packages

- name: 软连接
  file: state=link src=/application/mysql-5.6.42-linux-glibc2.12-x86_64 dest={{ mysql_dir }}
  when: p.stat.isreg is not defined

- name: 判断初始化
  stat: path=/data/{{ port }}
  register: p

- name: 准备mysql相关目录
  file: name=/data/{{ port }}/{{ item }} state=directory owner=mysql
  with_items:
  - data
  - log
  - bin
  when: p.stat.isreg is not defined
  
- name: 分发数据库配置
  template: src=my.cnf.j2 dest=/data/{{ port }}/my.cnf mode=0644
  when: p.stat.isreg is not defined

- name: 分发数据库启动关闭脚本
  template: src={{ item.src }} dest=/data/{{ port }}/bin/{{ item.des }} mode=0700 owner=mysql
  with_items:
  - {src: "shutdown.sh.j2", des: "shutdown.sh"}
  - {src: "startup.sh.j2", des: "startup.sh"}
  when: p.stat.isreg is not defined
  
- name: 分发数据库系统服务文件
  template: src=mysqld.j2 dest=/usr/lib/systemd/system/mysql{{ port }}.service mode=0700
  when: p.stat.isreg is not defined
  

- name: 初始化mysql
  shell: "/application/mysql/scripts/mysql_install_db \
        --basedir=/application/mysql \
        --datadir=/data/{{ port }}/data/ \
        --user=mysql"
  when: p.stat.isreg is not defined
  tags: db_init

- name: 修改mysqld_safe
  shell: sed -i "s#/usr/local/mysql#/application/mysql#g" /application/mysql/bin/mysqld_safe
  when: p.stat.isreg is not defined  

- name: 修改权限
  shell: "chown -R mysql.mysql /data/{{ port }}" 
  when: p.stat.isreg is not defined

- name: 启动数据库
  systemd:
    state: started
    name: mysql{{ port }}
  when: p.stat.isreg is not defined

- name: 配置数据库密码
  shell: "/application/mysql/bin/mysqladmin -uroot password {{ password }} -S /data/{{ port }}/mysql.sock"
  when: p.stat.isreg is not defined
